## 라이브러리 불러오기

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

## 데이터셋 만들기

In [2]:
col = ['장르', '재미있는', '연인', '사랑', '맹렬한', '빠른', '총격', '날으는']

genre = ['코미디', '액션', '코미디', '액션', '액션']
V1 = [1, 0, 2, 1, 0]
V2 = [1, 0, 1, 0, 0]
V3 = [2, 0, 0, 0, 1]
V4 = [0, 1, 0, 1, 0]
V5 = [0, 1, 1, 0, 1]
V6 = [0, 1, 0, 2, 1]
V7 = [0, 0, 1, 0, 1]

dic = {'장르':genre, 'V1':V1, 'V2':V2, 'V3':V3, 'V4':V4, 'V5':V5, 'V6':V6, 'V7':V7}

In [3]:
dic

{'장르': ['코미디', '액션', '코미디', '액션', '액션'],
 'V1': [1, 0, 2, 1, 0],
 'V2': [1, 0, 1, 0, 0],
 'V3': [2, 0, 0, 0, 1],
 'V4': [0, 1, 0, 1, 0],
 'V5': [0, 1, 1, 0, 1],
 'V6': [0, 1, 0, 2, 1],
 'V7': [0, 0, 1, 0, 1]}

dictionary 는 key 와 value값. 
data frame 만들 때는 pandas 안에 있음.
index 하고 싶으면 data.index,
column 하고 싶으면 data.columns

In [4]:
data = pd.DataFrame(dic)
data.columns = col
data

장르  재미있는  연인  사랑  맹렬한  빠른  총격  날으는
0  코미디     1   1   2    0   0   0    0
1   액션     0   0   0    1   1   1    0
2  코미디     2   1   0    0   1   0    1
3   액션     1   0   0    1   0   2    0
4   액션     0   0   1    0   1   1    1

## 0보다 큰 경우 'yes'로 반환하는 사용자 정의 함수를 생성

In [5]:
def convert(x) :
    if x > 0 :
        return 1
    else :
        return 0

In [6]:
convert(1)

1

In [7]:
convert(0)

0

In [8]:
data['재미있는']

0    1
1    0
2    2
3    1
4    0
Name: 재미있는, dtype: int64

apply라는 함수는 바로 함수 적용하게 해줌..

for문보다 성능이 좋음.

for문은 최대한 자제하는 것이 좋음(연산속도 그대로 반영하기 때문에 연산속도가 거의 최악임)


In [9]:
data['재미있는'].apply(convert)
# 등장했다는 것에 의미를 둠. 2같은것말고

0    1
1    0
2    1
3    1
4    0
Name: 재미있는, dtype: int64

In [10]:
data.columns[1:] ## 장르 빼고 1부터 불러와야함

Index(['재미있는', '연인', '사랑', '맹렬한', '빠른', '총격', '날으는'], dtype='object')

In [11]:
for i in data.columns[1:]:
    data[i] = data[i].apply(convert)
    
data

장르  재미있는  연인  사랑  맹렬한  빠른  총격  날으는
0  코미디     1   1   1    0   0   0    0
1   액션     0   0   0    1   1   1    0
2  코미디     1   1   0    0   1   0    1
3   액션     1   0   0    1   0   1    0
4   액션     0   0   1    0   1   1    1

## 나이브베이즈 모델 적용(Laplace 적용x)

MultinomialNB,,

먼저 parameters을 통해 모델을 만들고,
그 이후 attributes 을 통해 모델 뒤 함수 . 찍어서 뒤에 확인하는 것
https://scikit-learn.org/stable/modules/naive_bayes.html#multinomial-naive-bayes


In [12]:
from sklearn.naive_bayes import MultinomialNB

# alpha : laplace 추정기
# class_prior : 사전확률 직접 정의
# fit_prior : 사전확률 적합

model = MultinomialNB(alpha=0)
model.fit(data.iloc[:, 1:], data['장르']) 
## 모델 학습시켜주기
## 처음은 독립변수, 뒤에는 종속변수
## iloc -> 행 : 이니 행을 다 불러오고, 열은 1부터 불러오기
## dataframe 안의 자료 복습해오기

C:\Users\user\Anaconda3\lib\site-packages\sklearn\naive_bayes.py:512: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10
  'setting alpha = %.1e' % _ALPHA_MIN)


MultinomialNB(alpha=0)

class_prior 은 사전확률, 구분하고 싶은 최종,, 즉 코미디인지 액션인지.. 


학습시킬 때는 코미디인지 액션인지 다 알고 있음. 2/5 => 코미디일 확률 0.4.. 즉 이런 확률을 알고있는게 사전확률 (훈련시킬 때)


베이즈 정리 보면 B가 나왔을 때 A(코미디/액션)일 확률 -> 사후확률...? ,, p(A) = 사전확률

alpha 값만 잘 적용해주면 됨.

1) alpha=0 : 라플라스 적용하지 않았을 때

2) 라플라스 적용했을 때 

In [13]:
# alpha : alpha값 확인
model.alpha

0

In [14]:
# classes_ : 클래스 이름
model.classes_

array(['액션', '코미디'], dtype='<U3')

In [15]:
# class_count_ : 클래스 개수 반환
model.class_count_
## 앞에게 액션이었고, 클래스가 두개 있다는 뜻


array([3., 2.])

In [16]:
# feature_count_ : 각 클래스별 단어 개수 등장 횟수
## 연인같은 경우 액션은 0, 코미디는 2, 이런 개수를 세주는것
model.feature_count_
## 위에껀 액션, 아래는 코미디
## 퀴즈를 위해 여기를 잘 공부해보셈

array([[1., 0., 1., 2., 2., 3., 1.],
       [2., 2., 1., 0., 1., 0., 1.]])

In [17]:
# class_log_prior_ : class별 log를 씌운 사전확률
model.class_log_prior_

array([-0.51082562, -0.91629073])

In [18]:
## 수학적인 것 안에 np가 굉장히 많은 것을 차지하고 있음.
np.exp(model.class_log_prior_)

array([0.6, 0.4])

날으는을 보면 액션1, 코미디1 임.

사후확률로 보면 P(날으는/액션) = 1/3 (액션 3중에 날으는은 한번 들어감)

이걸 log, 즉 지수승 씌워주면 확률 구할 수 있음

In [19]:
# feature_log_prob_ : 단어별 log를 씌운 사후확률
np.exp(model.feature_log_prob_)

array([[1.00000000e-01, 1.00000000e-11, 1.00000000e-01, 2.00000000e-01,
        2.00000000e-01, 3.00000000e-01, 1.00000000e-01],
       [2.85714286e-01, 2.85714286e-01, 1.42857143e-01, 1.42857143e-11,
        1.42857143e-01, 1.42857143e-11, 1.42857143e-01]])

## 재미있는 맹렬한 빠른 단어가 나올경우

In [20]:
data.columns

Index(['장르', '재미있는', '연인', '사랑', '맹렬한', '빠른', '총격', '날으는'], dtype='object')

In [21]:
# test set 만들기
## 재미있는, 맹렬한, 빠른 만 나올 경우로 test 을 만들어본것임. 넣어줄때는 항상 array로.
test = np.array([1, 0, 0, 1, 1, 0, 0]).reshape(1, -1) 
## -1 이라는 것은 1행이 들어가면 자연스럽게 7개 들어가게끔.. -1 넣으면 행 지정된것 나머지 알아서 너가 계산해라. 
## -1, 1 들어가면 열이 하나고 행을 열하나에 맞게 너가 알아서 만들어라.
## -1, 1 하면 7, 1로 나올 것임
test.shape ## reshape을 하니 2차원 구조가 되었음.

(1, 7)

In [22]:
test ## 2차원구조임.

array([[1, 0, 0, 1, 1, 0, 0]])

In [23]:
# 예측
model.predict(test)

array(['액션'], dtype='<U3')

In [24]:
# 확률 확인
model.predict_proba(test) ## 앞이 액션, 뒤가 코미디. 결과보면 앞이 거의 1, 뒤에가 거의 0.

array([[1.00000000e+00, 9.71817298e-11]])

## 나이브베이즈 모델 적용(Laplace 적용o)

In [25]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB(alpha=1)
model.fit(data.iloc[:, 1:], data['장르'])


MultinomialNB(alpha=1)

In [26]:
# 예측
model.predict(test)

array(['액션'], dtype='<U3')

In [27]:
# 확률 확인
model.predict_proba(test)
## 이게 더 나음. 너무 극단적인 앞보다 나은것임

array([[0.71536991, 0.28463009]])

# QUIZ 2
### 베이즈 정리, 지금 함수를 쓰면 베이즈정리의 좌항으로 바로 계산하는데, 우항을 직접 계산해서 좌, 우가 맞다는 것을 보여주기
(월 11:59 까지)

## 데이터 불러오기

In [28]:
data = pd.read_csv("data/HouseVotes84.csv")

In [29]:
data
# V1 이라는 법안에 대해서 0번 사람이 찬성했는지 반대했는지 
# yes or no 한 것임.
# 그래서 이사람이 공화당인지 민주당인지 예측해보는 것임

Class   V1   V2 V3   V4   V5 V6   V7   V8   V9  V10  V11  V12 V13  \
0    republican    n    y  n    y    y  y    n    n    n    y  NaN    y   y   
1    republican    n    y  n    y    y  y    n    n    n    n    n    y   y   
2      democrat  NaN    y  y  NaN    y  y    n    n    n    n    y    n   y   
3      democrat    n    y  y    n  NaN  y    n    n    n    n    y    n   y   
4      democrat    y    y  y    n    y  y    n    n    n    n    y  NaN   y   
..          ...  ...  ... ..  ...  ... ..  ...  ...  ...  ...  ...  ...  ..   
429  republican    n    n  y    y    y  y    n    n    y    y    n    y   y   
430    democrat    n    n  y    n    n  n    y    y    y    y    n    n   n   
431  republican    n  NaN  n    y    y  y    n    n    n    n    y    y   y   
432  republican    n    n  n    y    y  y  NaN  NaN  NaN  NaN    n    y   y   
433  republican    n    y  n    y    y  y    n    n    n    y    n    y   y   

    V14  V15  V16  
0     y    n    y  
1     y    n  NaN  
2     y    n    n  
3     n    n    y  
4     y    y    y  
..   ..  ...  ...  
429   y    n    y  
430   n    n    y  
431   y    n    y  
432   y    n    y  
433   y  NaN    n  

[434 rows x 17 columns]

## Quiz
첫번째 사람 n 10개, y 5개면 이건 n.. (개수 많은것에 따라 결측치 측정하는 방법)
11번째 항에서 공화당이면 공화당인사람만 불러서 과반수인 것으로 채우기 등등의 방법이 있음.

hint ) 모든 사람이 결측치 있는 것은 아니고, 행에 NA 값 있는지 아닌지 확인하는 것 -> "is"
-> data.isna()

In [30]:
data.iloc[0].isna()

Class    False
V1       False
V2       False
V3       False
V4       False
V5       False
V6       False
V7       False
V8       False
V9       False
V10      False
V11       True
V12      False
V13      False
V14      False
V15      False
V16      False
Name: 0, dtype: bool

## 결측치 채우기

In [31]:
# 결측치가 있는 행만 불러오기
data.isna()

Class     V1     V2     V3     V4     V5     V6     V7     V8     V9  \
0    False  False  False  False  False  False  False  False  False  False   
1    False  False  False  False  False  False  False  False  False  False   
2    False   True  False  False   True  False  False  False  False  False   
3    False  False  False  False  False   True  False  False  False  False   
4    False  False  False  False  False  False  False  False  False  False   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
429  False  False  False  False  False  False  False  False  False  False   
430  False  False  False  False  False  False  False  False  False  False   
431  False  False   True  False  False  False  False  False  False  False   
432  False  False  False  False  False  False  False   True   True   True   
433  False  False  False  False  False  False  False  False  False  False   

       V10    V11    V12    V13    V14    V15    V16  
0    False   True  False  False  False  False  False  
1    False  False  False  False  False  False   True  
2    False  False  False  False  False  False  False  
3    False  False  False  False  False  False  False  
4    False  False   True  False  False  False  False  
..     ...    ...    ...    ...    ...    ...    ...  
429  False  False  False  False  False  False  False  
430  False  False  False  False  False  False  False  
431  False  False  False  False  False  False  False  
432   True  False  False  False  False  False  False  
433  False  False  False  False  False   True  False  

[434 rows x 17 columns]

In [32]:
temp = data.isna().sum(axis=1)

## 행 단위로 하려고 함. 따라서 행.

##V1 대로 하고 싶으면 axis = 0
##사람대로 하고 싶으면 axis = 1

## axis 계산할 때만 반대로 생각하기
## axis=0 은 column, axis=1 은 행.

temp[temp != 0].index
## True 인 값은 출력안하고 True 아닌 값만 출력
temp


0      1
1      1
2      2
3      1
4      1
      ..
429    0
430    0
431    1
432    4
433    1
Length: 434, dtype: int64

In [33]:
len(temp[temp != 0].index)

202

In [34]:
data.fillna('y', inplace=True)

##inplace true 는 데이터에 변수 담아줄 필요 없음. 그 자체가 변수.

In [35]:
data

Class V1 V2 V3 V4 V5 V6 V7 V8 V9 V10 V11 V12 V13 V14 V15 V16
0    republican  n  y  n  y  y  y  n  n  n   y   y   y   y   y   n   y
1    republican  n  y  n  y  y  y  n  n  n   n   n   y   y   y   n   y
2      democrat  y  y  y  y  y  y  n  n  n   n   y   n   y   y   n   n
3      democrat  n  y  y  n  y  y  n  n  n   n   y   n   y   n   n   y
4      democrat  y  y  y  n  y  y  n  n  n   n   y   y   y   y   y   y
..          ... .. .. .. .. .. .. .. .. ..  ..  ..  ..  ..  ..  ..  ..
429  republican  n  n  y  y  y  y  n  n  y   y   n   y   y   y   n   y
430    democrat  n  n  y  n  n  n  y  y  y   y   n   n   n   n   n   y
431  republican  n  y  n  y  y  y  n  n  n   n   y   y   y   y   n   y
432  republican  n  n  n  y  y  y  y  y  y   y   n   y   y   y   n   y
433  republican  n  y  n  y  y  y  n  n  n   y   n   y   y   y   y   n

[434 rows x 17 columns]

## n이면 0, y면 1 적용

In [36]:
def convert(x) :
    if x == 'y' :
        return 1
    else : 
        return 0

In [37]:
for i in data.columns[1:3]:
    data[i] = data[i].apply(convert)

In [38]:
data

Class  V1  V2 V3 V4 V5 V6 V7 V8 V9 V10 V11 V12 V13 V14 V15 V16
0    republican   0   1  n  y  y  y  n  n  n   y   y   y   y   y   n   y
1    republican   0   1  n  y  y  y  n  n  n   n   n   y   y   y   n   y
2      democrat   1   1  y  y  y  y  n  n  n   n   y   n   y   y   n   n
3      democrat   0   1  y  n  y  y  n  n  n   n   y   n   y   n   n   y
4      democrat   1   1  y  n  y  y  n  n  n   n   y   y   y   y   y   y
..          ...  ..  .. .. .. .. .. .. .. ..  ..  ..  ..  ..  ..  ..  ..
429  republican   0   0  y  y  y  y  n  n  y   y   n   y   y   y   n   y
430    democrat   0   0  y  n  n  n  y  y  y   y   n   n   n   n   n   y
431  republican   0   1  n  y  y  y  n  n  n   n   y   y   y   y   n   y
432  republican   0   0  n  y  y  y  y  y  y   y   n   y   y   y   n   y
433  republican   0   1  n  y  y  y  n  n  n   y   n   y   y   y   y   n

[434 rows x 17 columns]

## train test 분리

In [39]:
import random

# random seed 설정하기



x_data 는 독립변수 -> V1 ~ V16 까지 일것임.

In [40]:
x_data = data.iloc[:,1:] ## iloc 는 다 불러오는 것
y_data = data['Class']

In [41]:
from sklearn.model_selection import train_test_split

# train, test set분리 
X_train, X_test, y_train, y_test = train_test_split(x_data, y_data, 
                                                    test_size = 0.3, 
                                                    random_state = 7)
## random_state 는 무작위값. 100개 중 random 으로 70,30개 뽑는데, seed 값에 따라 7, 8 뽑는게 다 다름..
## random_state 여러개 해서 평균값 하는 경우도 많음( 한쪽에 치중되게 되었을 수도 있으니 )

## 나이브베이즈 모델 적용

In [42]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB(alpha = 1)

model.fit(X_train, y_train)

## 모델 훈련이 중요한게 아니라 데이터를 가지고 결측치를 어떻게 처리하는지가 중요함.
## 모델 훈련은 그냥 코드만 돌리면되어서 쉬움. 
## 결측치 하는데 90퍼센트를 써야함.

ValueError: could not convert string to float: 'n'

In [ ]:
# test 데이터로 예측
y_pred = model.predict(X_test)

In [ ]:
model.predict(X_test)

In [ ]:
# 정확도 확인
sum(y_pred == y_test) / len(y_test)